# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestCrearCuenta():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_crearCuenta(self):
    self.driver.get("http://127.0.0.1:5000/")
    self.driver.set_window_size(1920, 1055)
    self.driver.find_element(By.LINK_TEXT, "Sign In").click()
    self.driver.find_element(By.LINK_TEXT, "Register here").click()
    self.driver.find_element(By.NAME, "email").click()
    self.driver.find_element(By.NAME, "email").send_keys("prueba@gmail.com")
    self.driver.find_element(By.ID, "password").click()
    self.driver.find_element(By.ID, "password").send_keys("1q2w3e4r5t")
    self.driver.find_element(By.ID, "cpassword").send_keys("1q2w3e4r5t")
    self.driver.find_element(By.NAME, "firstName").send_keys("cami")
    self.driver.find_element(By.NAME, "firstName").click()
    self.driver.find_element(By.NAME, "firstName").click()
    element = self.driver.find_element(By.NAME, "firstName")
    actions = ActionChains(self.driver)
    actions.double_click(element).perform()
    self.driver.find_element(By.NAME, "firstName").send_keys("pru")
    self.driver.find_element(By.NAME, "lastName").send_keys("eba")
    self.driver.find_element(By.NAME, "Date Of Birth:").send_keys("11/10/1999")
    self.driver.find_element(By.NAME, "address1").send_keys("prueba")
    self.driver.find_element(By.NAME, "zipcode").send_keys("7777")
    self.driver.find_element(By.NAME, "city").send_keys("prueba")
    self.driver.find_element(By.NAME, "state").send_keys("prueba")
    self.driver.find_element(By.NAME, "country").send_keys("prueba")
    self.driver.find_element(By.CSS_SELECTOR, "p:nth-child(12) > input").click()
  
